

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "devops-poc.name" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts: 
    - {{ .Values.url }}
    secretName: quickstart-example-tls
  rules:
    - host: {{ .Values.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "devops-poc.name" . }}
                port:
                  number: {{ .Values.service.ingress.port }}